Repository simulationcraft/simc, pull requests merged in 2021-06, with the labels that each got.

#5965 windwalker APL updates
  engine/class_modules/apl/apl_monk.cpp
Labels: ActionPriorityList, Monk

#5967 [Death Knight] Update Rune of Sanguination to match live behavior
  engine/class_modules/sc_death_knight.cpp
Labels: DeathKnight

#5975 Shaman Elemental APL
  engine/class_modules/sc_shaman.cpp
Labels: ActionPriorityList, Shaman

#5924 Demotime APL
  engine/class_modules/warlock/sc_warlock.cpp
  engine/class_modules/warlock/sc_warlock_demonology.cpp
  profiles/generators/Tier26/T26_Generate_Warlock.simc
Labels: ActionPriorityList, Warlock

#5986 [Monk] Update necrolord windwalker apl
  engine/class_modules/apl/apl_monk.cpp
Labels: ActionPriorityList, Monk

#6013 [Death Knight] Initial T27 profiles
  profiles/T27_Raid.simc
  profiles/generators/Tier27/T27_Generate_Death_Knight.simc
Labels: DeathKnight

#6002 [Death Knight] First pass Dk legendaries 9.1
  engine/class_modules/sc_death_knight.cpp
Labels: DeathKnight

#6027 [Death Knight] Remove PTR checks
  engine/class_modules/sc_death_knight.cpp
  engine/player/unique_gear_shadowlands.cpp
Labels: DeathKnight

#6012 [Death Knight] 9.1 APL Updates
  engine/class_modules/apl/apl_death_knight.cpp
  profiles/generators/Tier27/T27_Generate_Death_Knight.simc
Labels: ActionPriorityList, DeathKnight

#6000 [Death Knight] Match shackle spread behavior to live
  engine/class_modules/sc_death_knight.cpp
Labels: DeathKnight

#6036 [Death Knight] Move unholy blight pet damage multiplier
  engine/class_modules/sc_death_knight.cpp
Labels: DeathKnight
