Repository simulationcraft/simc, pull requests merged in 2022-11, with the labels that each got.

#6975 [Evoker] Formulaic on use Trinkets
  engine/class_modules/apl/apl_evoker.cpp
Labels: ActionPriorityList, Dragonflight

#7041 [Evoker] Update Trinket Logic
  engine/class_modules/apl/apl_evoker.cpp
Labels: ActionPriorityList

#7040 [DK] Delete Shadowlands
  engine/class_modules/apl/apl_death_knight.cpp
  engine/class_modules/sc_death_knight.cpp
  engine/player/unique_gear_dragonflight.cpp
  engine/sim/sim.cpp
  engine/sim/sim.hpp
  profiles/Tier29/T29_Death_Knight_Frost.simc
  profiles/Tier29/T29_Death_Knight_Frost_2h.simc
  profiles/Tier29/T29_Death_Knight_Frost_DW.simc
  profiles/Tier29/T29_Death_Knight_Unholy.simc
  profiles/generators/Tier29/T29_Generate_Death_Knight.simc
Labels: DeathKnight

#7047 [Warlock] New CB/RoF rules and Cry havoc in cleave
  engine/class_modules/apl/warlock.cpp
Labels: Warlock
