Repository simulationcraft/simc, pull requests merged in 2022-09, with the labels that each got.

#6693 [Frost DK] Fix Buff up checks
  engine/class_modules/apl/apl_death_knight.cpp
Labels: DeathKnight, ActionPriorityList, Dragonflight

#6711 [Unholy DK] Dragonflight APL Updates
  dbc_extract3/dbc/generator.py
  engine/class_modules/apl/apl_death_knight.cpp
Labels: DeathKnight, ActionPriorityList, Dragonflight

#6716 [Frost DK] build 45569 Frost Rework
  engine/class_modules/sc_death_knight.cpp
Labels: DeathKnight, Dragonflight

#6718 [Frost DK] Dragonflight APL
  engine/class_modules/apl/apl_death_knight.cpp
Labels: DeathKnight, ActionPriorityList, Dragonflight

#6737 [Death Knight] Blood talents
  engine/class_modules/apl/apl_death_knight.cpp
  engine/class_modules/sc_death_knight.cpp
Labels: DeathKnight
