Repository simulationcraft/simc, pull requests merged in 2023-09, with the labels that each got.

#8039 [Vengeance] first pass at T31 implementation
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8054 [Vengeance] use correct spell ID for Fiery Resolve
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8062 [Vengeance] implement Calcified Spikes
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8064 [Vengeance] implement Retaliation
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8067 [Afflction] T31 Tier Set
  engine/class_modules/warlock/sc_warlock.cpp
  engine/class_modules/warlock/sc_warlock.hpp
  engine/class_modules/warlock/sc_warlock_affliction.cpp
Labels: Warlock

#8071 [Vengeance] restrict T31 2p triggers
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8103 [Demon Hunter] run clang-format
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8090 [Feral] T31 Class Set Implementation part 3
  engine/class_modules/sc_druid.cpp
Labels: Druid

#8106 [Havoc] implement new Serrated Glaive
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8091 [Feral] Implement AG
  engine/class_modules/sc_druid.cpp
Labels: Druid

#8109 [Demon Hunter] Spectral Sight procs Fodder to the Flame
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8114 [Demon Hunter] Implement AFI
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8129 [Demon Hunter] update class talent struct order
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8132 [Havoc] fix ability to use Sigil of Flame
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8133 [Demon Hunter] more accurate Precise/Concentrated Sigils
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#8134 [Demon Hunter] allow Spectral Sight to be cast pre-combat
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter
