Repository simulationcraft/simc, pull requests merged in 2023-07, with the labels that each got.

#7878 [Warlock] Fix T30 4pc for Affli Vile Taint
  engine/class_modules/warlock/sc_warlock_affliction.cpp
Labels: Warlock

#7863 [Warlock] Add Expression to Track Expiring IGB
  engine/class_modules/warlock/sc_warlock.cpp
Labels: Warlock

#7885 [Vengeance] fix Immolation Aura energize amt
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#7893 [Vengeance] fix Frailty damage mult
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#7848 [Warlock] Demo APL Improvements
  engine/class_modules/apl/warlock.cpp
Labels: Warlock, ActionPriorityList

#7935 [Vengeance] update APL
  engine/class_modules/apl/apl_demon_hunter.cpp
  engine/class_modules/apl/demon_hunter/vengeance.simc
  profiles/Tier29/T29_Demon_Hunter_Vengeance.simc
  profiles/Tier30/T30_Demon_Hunter_Vengeance.simc
Labels: DemonHunter

#7942 [Vengeance] update APL
  engine/class_modules/apl/apl_demon_hunter.cpp
  engine/class_modules/apl/demon_hunter/vengeance.simc
  profiles/Tier29/T29_Demon_Hunter_Vengeance.simc
  profiles/Tier30/T30_Demon_Hunter_Vengeance.simc
Labels: DemonHunter

#7955 [Vengeance] update APL
  engine/class_modules/apl/apl_demon_hunter.cpp
  engine/class_modules/apl/demon_hunter/vengeance.simc
  profiles/Tier29/T29_Demon_Hunter_Vengeance.simc
  profiles/Tier30/T30_Demon_Hunter_Vengeance.simc
Labels: DemonHunter

#7974 [Vengeance] update APL
  engine/class_modules/apl/apl_demon_hunter.cpp
  engine/class_modules/apl/demon_hunter/vengeance.simc
  profiles/Tier29/T29_Demon_Hunter_Vengeance.simc
  profiles/Tier30/T30_Demon_Hunter_Vengeance.simc
Labels: DemonHunter

#7980 [Demon Hunter] update Soul Fragment travel time
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#7983 [Demon Hunter] Soul Cleave is target capped
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter

#7985 [Vengeance] fix Spirit Bomb AoE cap
  engine/class_modules/sc_demon_hunter.cpp
Labels: DemonHunter
